export const DATA_SOURCES = 'dashboard/DATA_SOURCES'
export const DATA_SOURCES_PENDING = `${DATA_SOURCES}_PENDING`
export const DATA_SOURCES_FULFILLED = `${DATA_SOURCES}_FULFILLED`
export const DATA_SOURCES_REJECTED = `${DATA_SOURCES}_REJECTED`
